<a href="https://colab.research.google.com/github/mitchellmiskowski/Math311_Linear_Algebra_Projects/blob/main/Gram_Schmidt_Orthonormalization_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

Let's figure out some vector operations!!

In [20]:
# Create a vector
v = np.array([1,2,3,4])
v

array([1, 2, 3, 4])

In [13]:
# Add a vector to a vector
v + v

array([[2],
       [4],
       [6],
       [8]])

In [14]:
# Scale a vector
5 * v

array([[ 5],
       [10],
       [15],
       [20]])

In [15]:
(1/5) * v

array([[0.2],
       [0.4],
       [0.6],
       [0.8]])

In [18]:
# Norm of a vector
v.size

4

In [21]:
# Dot products:
v.dot(v)

np.int64(30)

In [22]:
np.linalg.norm(v)

np.float64(5.477225575051661)

In [23]:
np.sqrt(v.dot(v))

np.float64(5.477225575051661)

Gram-Schmidt Process for four vectors:

In [43]:
# Create the four vectors
r1 = np.array ([0,3,-3,0])
r2 = np.array ([2,6,-2,2])
r3 = np.array ([-2,1,-3,0])
r4 = np.array ([2,-4,-2,-4])

In [26]:
print("the first random vector is", r1)

the first random vector is [ 0  3 -3  0]


Let's process the first vector

In [27]:
# Choose r1
# Make temporary vector t1 = r1
t1 = r1
print(t1)

[ 0  3 -3  0]


In [29]:
# Normalize t1, and save it as our nice vector u1
n1 = np.sqrt(t1.dot(t1))
print(n1)
# Let's form u1
u1 = (1/n1) * t1
print("our first nice vector is u1: ", u1)

4.242640687119285
our first nice vector is u1:  [ 0.          0.70710678 -0.70710678  0.        ]


In [31]:
# Sanity check:
# Size of u1 is 1, and it is orthogonal to other nice vectors:
print(np.sqrt(u1.dot(u1)))

1.0


Process the second vector r2

In [32]:
# Choose r2
# Make a temporary vector t2 = r2 - (r2 . u1) u1
t2 = r2 - r2.dot(u1) * u1
print(t2)

[2. 2. 2. 2.]


In [33]:
# Normalize t2 and save it as u2:
n2 = np.sqrt(t2.dot(t2))
print(n2)
u2 = (1/n2) * t2
print("our second nice vector is u2: ", u2)

4.0
our second nice vector is u2:  [0.5 0.5 0.5 0.5]


In [34]:
# Sanity Check:
# Size of u2 is 1, and it is orthogonal to other nice vectors:
print(np.sqrt(u2.dot(u2)))
print(u1.dot(u2))

1.0
-3.3306690738754696e-16


Process the third vector r3

In [44]:
# Choose r3
# Make a temporary vector t3 = r3 - (r3 . u1) u1
t3 = r3 - r3.dot(u2) * u2 - r3.dot(u1) * u1
print(t3)

[-1.00000000e+00 -4.44089210e-16  1.33226763e-15  1.00000000e+00]


In [47]:
# Normalize t3 and save it as u3:
n3 = np.sqrt(t3.dot(t3))
print(n3)
u3 = (1/n3) * t3
print("our third nice vector is u3: ", u3)

1.4142135623730951
our third nice vector is u3:  [-7.07106781e-01 -3.14018492e-16  9.42055475e-16  7.07106781e-01]


In [46]:
# Sanity Check:
# Size of u3 is 1, and it is orthogonal to other nice vectors:
print(np.sqrt(u3.dot(u3)))
print(u1.dot(u3))
print(u2.dot(u3))

0.9999999999999999
-8.881784197001252e-16
6.106226635438361e-16


Process the fourth vector r4

In [48]:
# Choose r4
# Make a temporary vector t4 = r4 - (r4 . u1) u1
t4 = r4 - r4.dot(u1) * u1 - r4.dot(u2) * u2 - r4.dot(u3) * u3
print(t4)

[ 1. -1. -1.  1.]


In [49]:
# Normalize t4 and save it as u4:
n4 = np.sqrt(t4.dot(t4))
print(n4)
u4 = (1/n4) * t4
print("our third nice vector is u4: ", u4)

2.0000000000000004
our third nice vector is u4:  [ 0.5 -0.5 -0.5  0.5]


In [50]:
# Sanity Check:
# Size of u4 is 1, and it is orthogonal to other nice vectors:
print(np.sqrt(u4.dot(u4)))
print(u1.dot(u4))
print(u2.dot(u4))
print(u3.dot(u4))

0.9999999999999999
-2.4424906541753444e-15
1.1657341758564144e-15
5.551115123125783e-17


In [51]:
print("Our nice othornormed vectors are: ")
print(u1)
print(u2)
print(u3)
print(u4)

Our nice othornormed vectors are: 
[ 0.          0.70710678 -0.70710678  0.        ]
[0.5 0.5 0.5 0.5]
[-7.07106781e-01 -3.14018492e-16  9.42055475e-16  7.07106781e-01]
[ 0.5 -0.5 -0.5  0.5]
